name              'reprepro'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides custom resources for configuring reprepro apt repositories'
source_url        'https://github.com/sous-chefs/reprepro'
issues_url        'https://github.com/sous-chefs/reprepro/issues'
chef_version      '>= 15.3'
version           '2.1.4'

supports 'ubuntu', '>= 22.04'
supports 'debian', '>= 12.0'

depends 'apache2', '>= 9.0'
depends 'nginx', '>= 12.0'
