name              'reprepro'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures reprepro for an apt repository'
source_url        'https://github.com/sous-chefs/reprepro'
issues_url        'https://github.com/sous-chefs/reprepro/issues'
chef_version      '>= 15.0'
version           '2.1.4'

supports 'ubuntu'
supports 'debian'

depends 'apache2', '>= 3.0'
depends 'nginx', '>= 7.0'
depends 'gpg'
